language: ruby
rvm:
  - 2.1
install:
  - bundle install
  - gem install nokogiri -v 1.9.1
script:
  - bundle exec jekyll build
  #- bundle exec htmlproof --help 
  #- bundle exec htmlproof ./_site --only-4xx
branches:
  only:
  - master
env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer
