# Site settings
timezone: Europe/Berlin

baseurl: '' # the subpath of your site, e.g. /blog/
url: 'http://msoechting.de' # the base hostname & protocol for your site

title: 'Maximilian Söchting'
author: 'Maximilian Söchting'

languages: [ 'en', 'de' ]

google_font_sans_serif: 'Source+Sans+Pro:300'

flickr_user: ''
flickr_api_key: x

default_header_img_dimensions: 'width="1024" height="1024"'
default_thubmnail_img_dimensions: 'width="1024" height="720"'

# Handling Reading
safe: true
encoding: utf-8

# Build settings
markdown: kramdown

# Outputting
exclude: [
  'cibuild',
  'Gemfile',
  'Gemfile.lock',
  'package.json',
  'README.md',
  'vendor']

defaults:
  - scope:
      path: ''
    values:
      lang: en
      description: 'Personal website of Daniel Limberger, bachelor student at Hasso-Plattner-Institute in Potsdam. It enlists his projects, publications and contact information.'
  - scope:
      path: 'de'
    values:
      lang: de
      description: 'Persönliche Webseite von Maximilian Söchting, Bachelorstudent am Hasso-Plattner-Institut in Potsdam. Die Webseite listet Projekte, Veröffentlichungen und Kontaktdaten.'
  - scope:
      path: 'en'
    values:
      lang: en

# CSS Minification
sass:
  style: compressed
